spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attendance_db
    username: admin
    password: admin
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mvc:
    format:
      date-time: iso
api-server:
  url: http://localhost:3001
graphql:
  servlet:
    corsEnabled: true