const { randomNumber } = require('../utils.js')

const NAME = 'lessons';

const generate = () => {
  return [
    {
      id: 1,
      disciplineId: 1,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 157,
      dayId: 1,
      lessonWeekId: 1,
      bellId: 1,
    },
    {
      id: 2,
      disciplineId: 2,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 149,
      dayId: 1,
      lessonWeekId: 1,
      bellId: 2,
    },
    {
      id: 3,
      disciplineId: 3,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 159,
      dayId: 1,
      lessonWeekId: 1,
      bellId: 3,
    },
    {
      id: 4,
      disciplineId: 4,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: null,
      dayId: 1,
      lessonWeekId: 1,
      bellId: 4,
    },
    {
      id: 5,
      disciplineId: 5,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 155,
      dayId: 2,
      lessonWeekId: 1,
      bellId: 1,
    },
    {
      id: 6,
      disciplineId: 6,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 155,
      dayId: 2,
      lessonWeekId: 1,
      bellId: 2,
    },
    {
      id: 7,
      disciplineId: 8,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 146,
      dayId: 2,
      lessonWeekId: 1,
      bellId: 3,
    },
    {
      id: 8,
      disciplineId: 3,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 159,
      dayId: 2,
      lessonWeekId: 1,
      bellId: 4,
    },
    {
      id: 9,
      disciplineId: 2,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 149,
      dayId: 3,
      lessonWeekId: 1,
      bellId: 1,
    },
    {
      id: 10,
      disciplineId: 9,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 105,
      dayId: 3,
      lessonWeekId: 1,
      bellId: 2,
    },
    {
      id: 11,
      disciplineId: 7,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 147,
      dayId: 3,
      lessonWeekId: 1,
      bellId: 3,
    },
    {
      id: 11,
      disciplineId: 7,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 147,
      dayId: 3,
      lessonWeekId: 1,
      bellId: 3,
    },
    {
      id: 12,
      disciplineId: 5,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 155,
      dayId: 4,
      lessonWeekId: 1,
      bellId: 2,
    },
    {
      id: 13,
      disciplineId: 10,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 168,
      dayId: 4,
      lessonWeekId: 1,
      bellId: 3,
    },
    {
      id: 14,
      disciplineId: 1,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 157,
      dayId: 4,
      lessonWeekId: 1,
      bellId: 4,
    },
    {
      id: 15,
      disciplineId: 2,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 149,
      dayId: 5,
      lessonWeekId: 1,
      bellId: 1,
    },
    {
      id: 16,
      disciplineId: 6,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 155,
      dayId: 5,
      lessonWeekId: 1,
      bellId: 2,
    },
    {
      id: 17,
      disciplineId: 3,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 159,
      dayId: 4,
      lessonWeekId: 1,
      bellId: 3,
    },
    //////// 2 week ///////////
    {
      id: 18,
      disciplineId: 1,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 157,
      dayId: 1,
      lessonWeekId: 2,
      bellId: 1,
    },
    {
      id: 19,
      disciplineId: 2,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 149,
      dayId: 1,
      lessonWeekId: 2,
      bellId: 2,
    },
    {
      id: 20,
      disciplineId: 3,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 159,
      dayId: 1,
      lessonWeekId: 2,
      bellId: 3,
    },
    {
      id: 21,
      disciplineId: 4,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: null,
      dayId: 1,
      lessonWeekId: 2,
      bellId: 4,
    },
    {
      id: 22,
      disciplineId: 1,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 157,
      dayId: 2,
      lessonWeekId: 2,
      bellId: 1,
    },
    {
      id: 23,
      disciplineId: 7,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 146,
      dayId: 2,
      lessonWeekId: 2,
      bellId: 2,
    },
    {
      id: 24,
      disciplineId: 8,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 146,
      dayId: 2,
      lessonWeekId: 2,
      bellId: 3,
    },
    {
      id: 26,
      disciplineId: 2,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 149,
      dayId: 3,
      lessonWeekId: 2,
      bellId: 1,
    },
    {
      id: 27,
      disciplineId: 9,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 105,
      dayId: 3,
      lessonWeekId: 2,
      bellId: 2,
    },
    {
      id: 28,
      disciplineId: 7,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 147,
      dayId: 3,
      lessonWeekId: 2,
      bellId: 3,
    },
    {
      id: 29,
      disciplineId: 1,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 157,
      dayId: 4,
      lessonWeekId: 2,
      bellId: 1,
    },
    {
      id: 30,
      disciplineId: 5,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 155,
      dayId: 4,
      lessonWeekId: 2,
      bellId: 2,
    },
    {
      id: 31,
      disciplineId: 10,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 168,
      dayId: 4,
      lessonWeekId: 2,
      bellId: 3,
    },
    {
      id: 33,
      disciplineId: 5,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 155,
      dayId: 5,
      lessonWeekId: 2,
      bellId: 1,
    },
    {
      id: 34,
      disciplineId: 6,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 155,
      dayId: 5,
      lessonWeekId: 2,
      bellId: 2,
    },
    {
      id: 35,
      disciplineId: 3,
      teacherId: randomNumber(1, 15),
      groupId: 1,
      roomNumber: 159,
      dayId: 4,
      lessonWeekId: 2,
      bellId: 3,
    },
  ]
}

module.exports = {
  NAME, generate
}